import { puzzleRandom, shuffle } from './core.js';

const rows = [
  [
    'Ciencia',
    1,
    'Dos objetos chocan y quedan unidos. Si no actúan fuerzas externas, ¿qué se conserva?',
    'Cantidad de movimiento',
    'Energía cinética',
    'Velocidad de cada objeto',
    'Temperatura',
    'El momento total se conserva aunque parte de la energía cinética se transforme.',
  ],
  [
    'Ciencia',
    2,
    'Si un objeto duplica su velocidad sin cambiar su masa, su energía cinética…',
    'Se cuadruplica',
    'Se duplica',
    'Se reduce a la mitad',
    'No cambia',
    'La energía cinética es mv²/2.',
  ],
  [
    'Ciencia',
    2,
    'En el vacío se sueltan una bola de plomo y una pluma desde la misma altura. ¿Cuál cae más rápido?',
    'Caen igual',
    'Una bola de plomo',
    'Una pluma',
    'Depende del área',
    'Sin aire, ambos tienen la misma aceleración gravitatoria.',
  ],
  [
    'Ciencia',
    3,
    '¿Qué fenómeno demuestra que la luz puede comportarse como una onda?',
    'Interferencia',
    'Una sombra nítida',
    'La masa de un fotón',
    'Una batería descargada',
    'La superposición de ondas produce franjas de interferencia.',
  ],
  [
    'Ciencia',
    1,
    '¿Qué cambia al pasar la luz del aire al agua?',
    'Velocidad y longitud de onda',
    'Solo su frecuencia',
    'Su frecuencia y color necesariamente',
    'La carga de los fotones',
    'La frecuencia se mantiene; la velocidad y la longitud de onda cambian.',
  ],
  [
    'Ciencia',
    3,
    'En una onda sonora, el tono depende principalmente de…',
    'La frecuencia',
    'La amplitud',
    'La duración',
    'La distancia al oyente',
    'La frecuencia determina la altura del sonido; la amplitud se relaciona con la intensidad.',
  ],
  [
    'Ciencia',
    2,
    '¿Por qué un cubito de hielo flota en agua?',
    'El hielo es menos denso',
    'No tiene masa',
    'El agua lo magnetiza',
    'El frío lo empuja',
    'La estructura del hielo ocupa más volumen para la misma masa.',
  ],
  [
    'Ciencia',
    1,
    'En disoluciones diluidas, una de pH 3 tiene una concentración de H⁺ que, comparada con una de pH 5, es…',
    '100 veces mayor',
    '2 veces mayor',
    '10 veces mayor',
    '100 veces menor',
    'La escala de pH es logarítmica: dos unidades equivalen a un factor 100.',
  ],
  [
    'Ciencia',
    3,
    '¿Cuál de estas magnitudes es vectorial?',
    'Aceleración',
    'Energía',
    'Temperatura',
    'Masa',
    'La aceleración tiene módulo, dirección y sentido.',
  ],
  [
    'Ciencia',
    2,
    'Dos resistencias iguales conectadas en paralelo tienen una resistencia equivalente…',
    'La mitad de una',
    'El doble de una',
    'Igual a una',
    'Cuatro veces una',
    'Dos caminos iguales en paralelo reducen a la mitad la resistencia.',
  ],
  [
    'Ciencia',
    1,
    '¿Qué cantidad cambia entre dos isótopos del mismo elemento?',
    'El número de neutrones',
    'El número de protones',
    'El signo de la carga del protón',
    'El tipo de electrón',
    'Los isótopos comparten número atómico, pero no necesariamente neutrones.',
  ],
  [
    'Ciencia',
    3,
    'En un gas ideal a temperatura constante, si el volumen se reduce a la mitad, la presión…',
    'Se duplica',
    'Se reduce a la mitad',
    'Se cuadruplica',
    'No cambia',
    'La ley de Boyle mantiene constante el producto presión × volumen.',
  ],
  [
    'Vida',
    1,
    '¿Qué orgánulo realiza la fotosíntesis?',
    'Cloroplasto',
    'Mitocondria',
    'Ribosoma',
    'Lisosoma',
    'La fotosíntesis ocurre en los cloroplastos.',
  ],
  [
    'Vida',
    2,
    '¿Qué base del ARN ocupa el lugar de la timina del ADN?',
    'Uracilo',
    'Adenina',
    'Guanina',
    'Citosina',
    'El ARN utiliza uracilo; el ADN, timina.',
  ],
  [
    'Vida',
    3,
    'En los seres humanos, ¿qué proceso forma gametos con la mitad de cromosomas?',
    'Meiosis',
    'Mitosis',
    'Ósmosis',
    'Traducción',
    'La meiosis reduce a la mitad el número de cromosomas.',
  ],
  [
    'Vida',
    1,
    '¿Cuál de estos animales es un molusco?',
    'Pulpo',
    'Medusa',
    'Cangrejo',
    'Estrella de mar',
    'Los pulpos son moluscos cefalópodos.',
  ],
  [
    'Vida',
    2,
    '¿Qué grupo de plantas produce flores y frutos?',
    'Angiospermas',
    'Musgos',
    'Helechos',
    'Gimnospermas',
    'Las angiospermas protegen sus semillas dentro del fruto.',
  ],
  [
    'Vida',
    3,
    '¿Cómo se llama el movimiento de agua a través de una membrana semipermeable?',
    'Ósmosis',
    'Fagocitosis',
    'Fermentación',
    'Traducción',
    'En la ósmosis, el agua atraviesa una membrana selectiva.',
  ],
  [
    'Vida',
    1,
    '¿Qué estructura fabrica proteínas leyendo ARN mensajero?',
    'Ribosoma',
    'Centriolo',
    'Vacuola',
    'Membrana nuclear',
    'Los ribosomas traducen la secuencia del ARN en una proteína.',
  ],
  [
    'Vida',
    2,
    '¿Qué tienen en común las ballenas y los murciélagos?',
    'Son mamíferos',
    'Son peces',
    'Ponen huevos siempre',
    'Respiran por branquias',
    'Ambos grupos son mamíferos, pese a vivir en medios muy distintos.',
  ],
  [
    'Vida',
    3,
    '¿Cuál es la función principal del xilema de las plantas?',
    'Transportar agua y minerales',
    'Transportar solo azúcares',
    'Producir polen',
    'Fabricar semillas',
    'El xilema transporta agua y sales minerales desde la raíz.',
  ],
  [
    'Vida',
    1,
    '¿Qué molécula transporta gran parte del oxígeno en la sangre humana?',
    'Hemoglobina',
    'Insulina',
    'Colágeno',
    'Amilasa',
    'La hemoglobina de los glóbulos rojos transporta oxígeno.',
  ],
  [
    'Vida',
    2,
    '¿Qué pareja está formada por organismos eucariotas?',
    'Levadura y ameba',
    'Bacteria y virus',
    'Virus y levadura',
    'Bacteria y arquea',
    'Tanto las levaduras como las amebas tienen células eucariotas.',
  ],
  [
    'Vida',
    3,
    '¿Qué se conserva normalmente al desnaturalizar una proteína sin romper enlaces peptídicos?',
    'La secuencia de aminoácidos',
    'Su forma tridimensional',
    'Toda su actividad',
    'Su estructura cuaternaria',
    'La estructura primaria permanece; el plegamiento puede perderse.',
  ],
  [
    'Espacio',
    1,
    '¿Qué planeta tiene un día de rotación más largo que su año?',
    'Venus',
    'Marte',
    'Júpiter',
    'Neptuno',
    'Venus tarda unos 243 días terrestres en rotar y 225 en orbitar.',
  ],
  [
    'Espacio',
    2,
    '¿Dónde se encuentra el cinturón principal de asteroides?',
    'Entre Marte y Júpiter',
    'Entre Tierra y Marte',
    'Más allá de Neptuno',
    'Dentro de la órbita de Mercurio',
    'El cinturón principal está entre Marte y Júpiter.',
  ],
  [
    'Espacio',
    3,
    '¿Qué mide un año luz?',
    'Distancia',
    'Tiempo de una órbita',
    'Brillo',
    'Masa estelar',
    'Es la distancia recorrida por la luz en un año.',
  ],
  [
    'Espacio',
    1,
    '¿Qué causa principalmente las estaciones terrestres?',
    'La inclinación del eje',
    'La distancia a la Luna',
    'Las manchas solares',
    'Que el Sol cambie de tamaño',
    'La inclinación del eje cambia la iluminación de cada hemisferio.',
  ],
  [
    'Espacio',
    2,
    '¿Qué planeta tiene una gran mancha roja que es una tormenta?',
    'Júpiter',
    'Saturno',
    'Urano',
    'Venus',
    'La Gran Mancha Roja es una tormenta de Júpiter.',
  ],
  [
    'Espacio',
    3,
    'Una estrella de neutrones es…',
    'El resto muy denso de una estrella',
    'Una nube de hielo',
    'Un planeta sin atmósfera',
    'Una estrella recién formada',
    'Es lo que queda cuando el núcleo de ciertas estrellas grandes colapsa.',
  ],
  [
    'Espacio',
    1,
    '¿Qué fase lunar corresponde a un eclipse solar?',
    'Luna nueva',
    'Luna llena',
    'Cuarto creciente',
    'Cuarto menguante',
    'La Luna debe estar entre la Tierra y el Sol.',
  ],
  [
    'Espacio',
    2,
    '¿Qué fenómeno explica el corrimiento al rojo cosmológico de galaxias lejanas?',
    'La expansión del espacio',
    'El polvo vuelve roja toda luz',
    'Las estrellas solo emiten rojo',
    'La gravedad terrestre',
    'La expansión estira la longitud de onda de la luz durante su viaje.',
  ],
  [
    'Espacio',
    3,
    '¿Cuál de estas lunas orbita Saturno?',
    'Titán',
    'Europa',
    'Ío',
    'Ganímedes',
    'Titán es de Saturno; las otras tres orbitan Júpiter.',
  ],
  [
    'Espacio',
    1,
    '¿Qué planeta gira con su eje tan inclinado que parece estar de lado?',
    'Urano',
    'Mercurio',
    'Marte',
    'Júpiter',
    'El eje de Urano tiene una inclinación cercana a 98 grados.',
  ],
  [
    'Espacio',
    2,
    '¿Qué tipo de galaxia es la Vía Láctea?',
    'Espiral barrada',
    'Elíptica gigante',
    'Irregular sin estructura',
    'Anular perfecta',
    'La Vía Láctea es una galaxia espiral con barra central.',
  ],
  [
    'Espacio',
    3,
    '¿Cuál es la principal fuente de energía del Sol actualmente?',
    'Fusión de hidrógeno',
    'Combustión de oxígeno',
    'Fisión de uranio',
    'Caída de meteoritos',
    'En el núcleo se fusiona hidrógeno para formar helio.',
  ],
  [
    'Tierra',
    1,
    '¿Qué roca se forma al enfriarse el magma?',
    'Ígnea',
    'Sedimentaria siempre',
    'Metamórfica siempre',
    'Orgánica',
    'La solidificación del magma o lava produce rocas ígneas.',
  ],
  [
    'Tierra',
    2,
    '¿Qué línea separa las cuencas que desembocan hacia lados distintos?',
    'Divisoria de aguas',
    'Isobara',
    'Meridiano cero',
    'Línea de costa',
    'Una divisoria marca el límite entre cuencas hidrográficas.',
  ],
  [
    'Tierra',
    3,
    '¿Qué indica una isobara en un mapa meteorológico?',
    'Igual presión',
    'Igual temperatura',
    'Igual precipitación',
    'Igual altitud',
    'Las isobaras unen puntos de igual presión atmosférica.',
  ],
  [
    'Tierra',
    1,
    '¿Cuál de estos países no tiene costa marítima?',
    'Bolivia',
    'Ecuador',
    'Uruguay',
    'Surinam',
    'Bolivia es un país sin litoral marítimo.',
  ],
  [
    'Tierra',
    2,
    '¿Qué cordillera se asocia al choque entre las placas india y euroasiática?',
    'Himalaya',
    'Andes',
    'Apalaches',
    'Urales',
    'La colisión continental formó y sigue elevando el Himalaya.',
  ],
  [
    'Tierra',
    3,
    '¿Qué capa terrestre es principalmente líquida?',
    'Núcleo externo',
    'Núcleo interno',
    'Corteza continental',
    'Litosfera completa',
    'El núcleo externo es líquido; el interno es sólido.',
  ],
  [
    'Tierra',
    1,
    '¿Qué país ocupa gran parte de la península de Anatolia?',
    'Turquía',
    'Grecia',
    'Egipto',
    'Irán',
    'La mayor parte de Turquía está en Anatolia.',
  ],
  [
    'Tierra',
    2,
    '¿Cuál es el desierto más grande si también contamos los desiertos polares?',
    'Antártida',
    'Sahara',
    'Gobi',
    'Atacama',
    'Un desierto se define por su escasa precipitación, no por el calor.',
  ],
  [
    'Tierra',
    3,
    '¿Por qué hay mareas vivas cerca de luna nueva y luna llena?',
    'Se alinean las fuerzas de Sol y Luna',
    'La Luna deja de atraer',
    'La Tierra frena su giro',
    'El océano se calienta mucho',
    'La alineación refuerza las diferencias de marea.',
  ],
  [
    'Tierra',
    1,
    '¿Qué océano baña la costa oriental de África?',
    'Índico',
    'Atlántico',
    'Ártico',
    'Pacífico',
    'La costa oriental africana mira al océano Índico.',
  ],
  [
    'Tierra',
    2,
    '¿Qué corriente fría recorre la costa de Perú y Chile?',
    'Humboldt',
    'Golfo',
    'Kuroshio',
    'Agulhas',
    'La corriente de Humboldt influye en el clima y las pesquerías regionales.',
  ],
  [
    'Tierra',
    3,
    '¿Qué escala describe la acidez, no la dureza de un mineral?',
    'pH',
    'Mohs',
    'Richter',
    'Beaufort',
    'Mohs mide dureza; pH, acidez o basicidad.',
  ],
  [
    'Lengua',
    1,
    '¿Cuál contiene un hiato?',
    'País',
    'Causa',
    'Cielo',
    'Puente',
    'En país, las vocales se pronuncian en sílabas distintas.',
  ],
  [
    'Lengua',
    2,
    '¿Qué palabra es un palíndromo?',
    'Reconocer',
    'Recorrer',
    'Recordar',
    'Repartir',
    'Reconocer se lee igual de izquierda a derecha y al revés.',
  ],
  [
    'Lengua',
    3,
    'En «Ojalá venga», ¿qué modo verbal tiene «venga»?',
    'Subjuntivo',
    'Indicativo',
    'Infinitivo',
    'Gerundio',
    'El deseo se expresa aquí con presente de subjuntivo.',
  ],
  [
    'Lengua',
    1,
    '¿Cuál de estas palabras es esdrújula?',
    'Brújula',
    'Reloj',
    'Azúcar',
    'Papel',
    'Brújula lleva la fuerza en la antepenúltima sílaba.',
  ],
  [
    'Lengua',
    2,
    '«Sus dientes eran perlas» es un ejemplo de…',
    'Metáfora',
    'Onomatopeya',
    'Enumeración',
    'Hipérbaton',
    'La frase identifica dos realidades por una semejanza.',
  ],
  [
    'Lengua',
    3,
    '¿Qué relación hay entre «absorber» y «absolver»?',
    'Paronimia',
    'Antonimia',
    'Sinonimia',
    'Homografía',
    'Los parónimos tienen formas parecidas y significados diferentes.',
  ],
  [
    'Lengua',
    1,
    '¿Cuál es el plural de «régimen»?',
    'Regímenes',
    'Régimens',
    'Régimenes',
    'Regímen',
    'El plural cambia la posición escrita de la tilde: regímenes.',
  ],
  [
    'Lengua',
    2,
    'En «Se venden libros», el verbo concuerda con…',
    'Libros',
    'Se',
    'Una persona omitida necesariamente',
    'Nada',
    'Es una pasiva refleja: libros es el sujeto plural.',
  ],
  [
    'Lengua',
    3,
    '¿Qué figura repite palabras al principio de varios versos o frases?',
    'Anáfora',
    'Elipsis',
    'Metonimia',
    'Ironía',
    'La anáfora repite un inicio para crear énfasis o ritmo.',
  ],
  [
    'Lengua',
    1,
    '¿Qué palabra no es un adverbio?',
    'Lentitud',
    'Ayer',
    'Aquí',
    'Quizá',
    'Lentitud es un sustantivo.',
  ],
  [
    'Lengua',
    2,
    '¿Qué forma está bien escrita?',
    'Excepción',
    'Escepción',
    'Exepción',
    'Excepsión',
    'La grafía correcta es excepción.',
  ],
  [
    'Lengua',
    3,
    '¿Qué idioma es una lengua romance?',
    'Rumano',
    'Alemán',
    'Griego',
    'Húngaro',
    'El rumano deriva del latín, como el español y el francés.',
  ],
  [
    'Arte',
    1,
    '¿Quién escribió «La metamorfosis»?',
    'Franz Kafka',
    'Jorge Luis Borges',
    'Albert Camus',
    'Julio Cortázar',
    'La novela corta de Kafka comienza con la transformación de Gregor Samsa.',
  ],
  [
    'Arte',
    2,
    '¿Qué técnica pictórica utiliza pequeños puntos de color?',
    'Puntillismo',
    'Mosaico',
    'Grabado al aguafuerte',
    'Fresco',
    'El puntillismo construye imágenes mediante puntos de color.',
  ],
  [
    'Arte',
    3,
    '¿Qué autor creó Macondo?',
    'Gabriel García Márquez',
    'Mario Vargas Llosa',
    'Juan Rulfo',
    'Miguel de Unamuno',
    'Macondo es central en Cien años de soledad.',
  ],
  [
    'Arte',
    1,
    '¿Qué pintor realizó «Las meninas»?',
    'Diego Velázquez',
    'Francisco de Goya',
    'El Greco',
    'Salvador Dalí',
    'Velázquez pintó Las meninas en 1656.',
  ],
  [
    'Arte',
    2,
    '¿Cómo se organiza un haiku japonés tradicional?',
    'Tres partes de 5, 7 y 5 moras',
    'Cuatro versos de ocho sílabas',
    'Dos versos rimados',
    'Una estrofa de catorce versos',
    'Las moras miden la duración de los sonidos en japonés; no coinciden exactamente con las sílabas del español.',
  ],
  [
    'Arte',
    3,
    '¿Quién escribió «Ficciones»?',
    'Jorge Luis Borges',
    'Pablo Neruda',
    'Federico García Lorca',
    'Isabel Allende',
    'Ficciones reúne relatos de Borges.',
  ],
  [
    'Arte',
    1,
    '¿Qué movimiento se asocia especialmente con Salvador Dalí?',
    'Surrealismo',
    'Realismo socialista',
    'Neoclasicismo',
    'Arte románico',
    'Dalí es una figura muy conocida del surrealismo.',
  ],
  [
    'Arte',
    2,
    '¿Qué es el claroscuro?',
    'Contraste entre luz y sombra',
    'Pintura hecha solo con azul',
    'Una técnica de escultura en hielo',
    'Ausencia total de perspectiva',
    'El claroscuro modela formas mediante luces y sombras.',
  ],
  [
    'Arte',
    3,
    '¿En qué novela el capitán Ahab persigue una ballena blanca?',
    'Moby-Dick',
    'La isla del tesoro',
    'Robinson Crusoe',
    'Los viajes de Gulliver',
    'La persecución de la ballena organiza la novela de Herman Melville.',
  ],
  [
    'Arte',
    1,
    '¿Qué edificio es una obra destacada de Antoni Gaudí?',
    'Sagrada Familia',
    'Museo del Prado',
    'Palacio de Versalles',
    'Ópera de Sídney',
    'Gaudí dedicó buena parte de su vida a la Sagrada Familia.',
  ],
  [
    'Arte',
    2,
    '¿Qué caracteriza a un soneto clásico en cuanto al número de versos?',
    'Catorce',
    'Diez',
    'Doce',
    'Dieciséis',
    'El soneto clásico tiene catorce versos.',
  ],
  [
    'Arte',
    3,
    '¿Qué artista pintó «La noche estrellada» de 1889?',
    'Vincent van Gogh',
    'Claude Monet',
    'Paul Cézanne',
    'Edvard Munch',
    'Van Gogh la pintó durante su estancia en Saint-Rémy.',
  ],
  [
    'Tecnología',
    1,
    '¿Qué estructura de datos sigue el orden «último en entrar, primero en salir»?',
    'Pila',
    'Cola',
    'Árbol ordenado',
    'Conjunto',
    'En una pila sale primero lo último que entró. En una cola sale primero lo que entró primero.',
  ],
  [
    'Tecnología',
    2,
    '¿Qué hace DNS normalmente?',
    'Relaciona nombres de dominio con direcciones IP',
    'Comprime imágenes',
    'Cifra todos los archivos',
    'Alimenta el procesador',
    'DNS permite resolver nombres como un dominio a direcciones de red.',
  ],
  ['Tecnología', 3, 'En binario, ¿cuánto vale 10110?', '22', '18', '26', '20', '16 + 4 + 2 = 22.'],
  [
    'Tecnología',
    1,
    '¿Qué formato describe imágenes mediante formas vectoriales?',
    'SVG',
    'JPEG',
    'MP3',
    'WAV',
    'SVG almacena formas y trazados escalables.',
  ],
  [
    'Tecnología',
    2,
    '¿Cuál suele ser la complejidad de la búsqueda binaria en una lista ordenada?',
    'O(log n)',
    'O(n²)',
    'O(n!)',
    'O(2ⁿ)',
    'Cada comparación descarta aproximadamente la mitad de los elementos.',
  ],
  [
    'Tecnología',
    3,
    '¿Qué distingue a una función de resumen criptográfico de un cifrado que se puede deshacer?',
    'No está diseñada para recuperar la entrada',
    'Siempre produce archivos más grandes',
    'Necesita una contraseña para leerse',
    'Solo admite números',
    'Un resumen criptográfico no incluye un paso de descifrado para recuperar los datos originales.',
  ],
  [
    'Tecnología',
    1,
    '¿Cuántos valores distintos se pueden representar con ocho dígitos binarios?',
    '256',
    '128',
    '8',
    '512',
    'Cada dígito puede ser 0 o 1, así que hay 2⁸ combinaciones.',
  ],
  [
    'Tecnología',
    2,
    '¿Qué significa que una compresión sea «sin pérdida»?',
    'Se recupera exactamente el original',
    'No ocupa nada de espacio',
    'Solo funciona con texto',
    'No necesita descompresión',
    'No se descarta información necesaria para reconstruir el original.',
  ],
  [
    'Tecnología',
    3,
    '¿Qué protocolo aporta cifrado a las conexiones HTTPS?',
    'TLS',
    'FTP',
    'UDP por sí solo',
    'DNS',
    'HTTPS utiliza TLS para proteger el transporte.',
  ],
  [
    'Tecnología',
    1,
    '¿Qué tipo de memoria pierde sus datos cuando apagas el equipo?',
    'RAM',
    'SSD',
    'Disco óptico',
    'Memoria USB',
    'La RAM necesita energía para conservar sus datos.',
  ],
  [
    'Tecnología',
    2,
    '¿Qué devuelve la operación lógica XOR de verdadero y verdadero?',
    'Falso',
    'Verdadero',
    'Un número aleatorio',
    'No está definida',
    'XOR es verdadero cuando las entradas son diferentes.',
  ],
  [
    'Tecnología',
    3,
    '¿Qué problema evita principalmente una transacción atómica?',
    'Que una operación quede aplicada a medias',
    'Toda caída de Internet',
    'Todos los ataques informáticos',
    'Que los datos ocupen espacio',
    'Una transacción atómica se aplica entera o no se aplica.',
  ],
  [
    'Números',
    1,
    'Si un precio sube un 20 % y luego baja un 20 %, queda…',
    'Un 4 % por debajo',
    'Igual',
    'Un 4 % por encima',
    'Un 20 % por debajo',
    '1,20 × 0,80 = 0,96.',
  ],
  [
    'Números',
    2,
    'Lanzas dos dados normales de seis caras. ¿Qué suma puede salir de más formas?',
    '7',
    '6',
    '8',
    '9',
    'El 7 tiene seis parejas ordenadas posibles.',
  ],
  [
    'Números',
    3,
    '¿Cuántas diagonales tiene un hexágono?',
    '9',
    '6',
    '12',
    '15',
    'n(n−3)/2 da 6×3/2 = 9.',
  ],
  [
    'Números',
    1,
    '¿Cuál es la mediana de 2, 3, 9, 10 y 100?',
    '9',
    '24,8',
    '10',
    '3',
    'La mediana es el valor central de la lista ordenada.',
  ],
  [
    'Números',
    2,
    '¿Cuántos apretones hay si cinco personas se saludan una vez por pareja?',
    '10',
    '20',
    '5',
    '25',
    'Hay 5×4/2 parejas.',
  ],
  [
    'Números',
    3,
    'Lanzas tres monedas sin trucar. ¿Qué probabilidad hay de que salgan exactamente dos caras?',
    '3/8',
    '1/2',
    '1/4',
    '1/8',
    'Hay tres resultados favorables entre ocho posibles.',
  ],
  [
    'Números',
    1,
    '¿Cuál es el mínimo común múltiplo de 6 y 8?',
    '24',
    '48',
    '14',
    '12',
    '24 es el menor entero positivo divisible entre ambos.',
  ],
  [
    'Números',
    2,
    'Una rueda gira 450°. ¿Cuál es su giro equivalente dentro de una vuelta?',
    '90°',
    '45°',
    '180°',
    '270°',
    '450 − 360 = 90.',
  ],
  [
    'Números',
    3,
    '¿Cuál es la suma de los ángulos interiores de un pentágono plano?',
    '540°',
    '360°',
    '450°',
    '720°',
    'Se puede dividir en tres triángulos: 3×180°.',
  ],
  [
    'Números',
    1,
    'Si todos los A son B, ¿qué afirmación es necesariamente cierta?',
    'Ningún A está fuera de B',
    'Todos los B son A',
    'Ningún B es A',
    'Existen exactamente dos A',
    'La inclusión A dentro de B no obliga a que B esté dentro de A.',
  ],
  [
    'Números',
    2,
    '¿Cuántos subconjuntos tiene un conjunto de cuatro elementos?',
    '16',
    '8',
    '12',
    '24',
    'Cada elemento puede estar o no: 2⁴.',
  ],
  [
    'Números',
    3,
    'Un cuadrado de lado 6 tiene una diagonal de longitud…',
    '6√2',
    '12',
    '3√2',
    '√6',
    'Por Pitágoras, la diagonal es el lado multiplicado por √2.',
  ],
  [
    'Historia',
    1,
    '¿Cuál era una de las principales formas de escritura del antiguo Egipto?',
    'Jeroglífica',
    'Cuneiforme exclusivamente',
    'Hangul',
    'Alfabeto cirílico',
    'La escritura jeroglífica es una de las escrituras del antiguo Egipto.',
  ],
  [
    'Historia',
    2,
    '¿Qué civilización construyó Machu Picchu?',
    'Inca',
    'Maya',
    'Azteca',
    'Olmeca',
    'Machu Picchu pertenece al mundo inca.',
  ],
  [
    'Historia',
    3,
    '¿En qué año cayó Constantinopla ante los otomanos?',
    '1453',
    '1492',
    '1517',
    '1415',
    'La conquista otomana de Constantinopla ocurrió en 1453.',
  ],
  [
    'Historia',
    1,
    '¿Con qué invento europeo del siglo XV se asocia a Gutenberg?',
    'Imprenta de tipos móviles',
    'Telégrafo',
    'Máquina de vapor',
    'Telescopio',
    'Gutenberg desarrolló un sistema de imprenta de tipos móviles metálicos en Europa.',
  ],
  [
    'Historia',
    2,
    '¿Qué documento inglés de 1215 limitó ciertos poderes del rey?',
    'Carta Magna',
    'Declaración de Independencia',
    'Código napoleónico',
    'Tratado de Tordesillas',
    'La Carta Magna se acordó en Inglaterra en 1215.',
  ],
  [
    'Historia',
    3,
    '¿Qué piedra ayudó a descifrar los jeroglíficos egipcios?',
    'Piedra de Rosetta',
    'Piedra del Sol',
    'Estela de Hammurabi',
    'Piedra de Scone',
    'La Piedra de Rosetta conserva versiones de un decreto en distintas escrituras.',
  ],
  [
    'Historia',
    1,
    '¿Qué navegante completó al mando la primera circunnavegación tras la muerte de Magallanes?',
    'Juan Sebastián Elcano',
    'Cristóbal Colón',
    'Vasco da Gama',
    'James Cook',
    'Elcano condujo la expedición superviviente de vuelta en 1522.',
  ],
  [
    'Historia',
    2,
    '¿Qué ciudad fue la capital del Imperio bizantino?',
    'Constantinopla',
    'Alejandría',
    'Atenas',
    'Venecia',
    'Constantinopla fue su capital durante más de un milenio.',
  ],
  [
    'Historia',
    3,
    '¿Qué tratado de 1494 dividió zonas de expansión entre Castilla y Portugal?',
    'Tordesillas',
    'Versalles',
    'Utrecht',
    'Westfalia',
    'El Tratado de Tordesillas fijó una línea de demarcación atlántica.',
  ],
  [
    'Historia',
    1,
    '¿Qué civilización usó la escritura cuneiforme en sus orígenes?',
    'Sumeria',
    'Inca',
    'Vikinga',
    'Micénica',
    'La escritura cuneiforme surgió en Mesopotamia con los sumerios.',
  ],
  [
    'Historia',
    2,
    '¿Qué acontecimiento se asocia al año 1789 en Francia?',
    'Inicio de la Revolución francesa',
    'Caída de Napoleón',
    'Comuna de París',
    'Fin de la Primera Guerra Mundial',
    'La Revolución francesa comenzó en 1789.',
  ],
  [
    'Historia',
    3,
    '¿Qué emperador romano dio nombre a un famoso muro en Britania?',
    'Adriano',
    'Augusto',
    'Nerón',
    'Trajano',
    'El muro de Adriano marcaba una frontera en el norte de la Britania romana.',
  ],
  [
    'Música',
    1,
    'En la afinación habitual de un piano, ¿cuántos semitonos hay en una octava?',
    '12',
    '7',
    '8',
    '6',
    'Una octava se divide en doce semitonos iguales.',
  ],
  [
    'Música',
    2,
    '¿Qué intervalo hay de do a sol ascendentes dentro de una octava?',
    'Quinta justa',
    'Cuarta justa',
    'Tercera mayor',
    'Sexta menor',
    'Do-re-mi-fa-sol: una quinta justa.',
  ],
  [
    'Música',
    3,
    'En 6/8, ¿cuál es la agrupación habitual de las seis corcheas?',
    'Dos grupos de tres',
    'Tres grupos de dos siempre',
    'Un grupo de cuatro y uno de dos siempre',
    'Seis negras',
    'El 6/8 es normalmente un compás compuesto de dos tiempos.',
  ],
  [
    'Música',
    1,
    '¿Qué indicación pide disminuir gradualmente la intensidad?',
    'Diminuendo',
    'Crescendo',
    'Accelerando',
    'Staccato',
    'Diminuendo reduce la intensidad; no necesariamente la velocidad.',
  ],
  [
    'Música',
    2,
    '¿Qué instrumento pertenece a los de viento-madera aunque normalmente se fabrique en metal?',
    'Saxofón',
    'Trombón',
    'Trompeta',
    'Tuba',
    'El saxofón usa una lengüeta y se clasifica como viento-madera.',
  ],
  [
    'Música',
    3,
    '¿Qué escala menor comparte armadura con do mayor?',
    'La menor',
    'Do menor',
    'Mi menor',
    'Re menor',
    'La menor es la relativa menor de do mayor.',
  ],
  [
    'Música',
    1,
    '¿Qué símbolo eleva normalmente una nota un semitono?',
    'Sostenido',
    'Bemol',
    'Becuadro siempre',
    'Calderón',
    'El sostenido eleva la nota un semitono.',
  ],
  [
    'Música',
    2,
    '¿Qué significa «a cappella»?',
    'Cantar sin acompañamiento instrumental',
    'Tocar solo percusión',
    'Cantar siempre al unísono',
    'Interpretar muy deprisa',
    'La expresión se usa para música vocal sin instrumentos.',
  ],
  [
    'Música',
    3,
    '¿Qué intervalo resulta al invertir una tercera mayor?',
    'Sexta menor',
    'Quinta justa',
    'Tercera menor',
    'Séptima mayor',
    'Los intervalos invertidos suman nueve en su número; mayor pasa a menor.',
  ],
  [
    'Música',
    1,
    '¿Quién compuso «Las cuatro estaciones»?',
    'Antonio Vivaldi',
    'Johann Sebastian Bach',
    'Wolfgang Amadeus Mozart',
    'Frédéric Chopin',
    'Son cuatro conciertos para violín de Vivaldi.',
  ],
  [
    'Música',
    2,
    '¿Qué es una síncopa?',
    'Un desplazamiento del acento hacia una parte débil',
    'Un silencio al final obligatorio',
    'Una afinación más grave',
    'Un cambio de instrumento',
    'La síncopa altera la acentuación esperada del pulso.',
  ],
  [
    'Música',
    3,
    'En afinación habitual de guitarra, ¿qué pareja de cuerdas consecutivas forma una tercera mayor?',
    'Sol y si',
    'Mi grave y la',
    'La y re',
    'Si y mi agudo',
    'La afinación estándar usa cuartas salvo entre sol y si.',
  ],
];

export const TRIVIA = rows.map(
  ([category, difficulty, question, correct, a, b, c, explanation], id) => ({
    id,
    category,
    difficulty,
    question,
    correct,
    options: [correct, a, b, c],
    explanation,
  }),
);
export const QUIZ_LENGTH = 12;
export const MISTAKE_LIMIT = 3;

export function createQuiz(seed, attempt = 0, previous = []) {
  const random = puzzleRandom(seed, 0, attempt);
  for (let retry = 0; retry < 100; retry++) {
    const selected = [1, 2, 3].flatMap((level) =>
      shuffle(
        TRIVIA.filter((q) => q.difficulty === level && !previous.includes(q.id)),
        random,
      ).slice(0, 4),
    );
    if (new Set(selected.map((q) => q.category)).size >= 7)
      return shuffle(
        selected.map((q) => q.id),
        random,
      );
  }
  return shuffle(
    [1, 2, 3].flatMap((level) =>
      TRIVIA.filter((q) => q.difficulty === level && !previous.includes(q.id))
        .slice(0, 4)
        .map((q) => q.id),
    ),
    random,
  );
}

export function triviaOptions(question, seed, attempt) {
  return shuffle(question.options, puzzleRandom(seed, question.id + 1, attempt));
}

export function trivia(ctx) {
  const { root, stage } = ctx;
  let attempt = ctx.state.attempt || 0;
  let quiz = ctx.state.quiz || createQuiz(stage.seed, attempt),
    answers = ctx.state.answers || [];
  let reveal = ctx.state.reveal || false;
  function save() {
    ctx.patch({ attempt, quiz, answers, reveal });
  }
  function paint(message = '') {
    const mistakes = answers.filter((answer) => !answer.correct).length;
    if (answers.length === QUIZ_LENGTH && !reveal)
      return ctx.win(`¡${QUIZ_LENGTH - mistakes} respuestas correctas! Ya tienes tu estrella.`);
    const index = reveal ? answers.length - 1 : answers.length;
    const question = TRIVIA[quiz[index]],
      options = triviaOptions(question, stage.seed, attempt);
    root.innerHTML = `
      <div class="round-label">
        PREGUNTA ${index + 1} / ${QUIZ_LENGTH} · ${question.category.toUpperCase()} · NIVEL
        ${question.difficulty}
      </div>
      <p class="game-instruction">
        <strong>Al tercer error entre todas las preguntas, empiezas un cuestionario nuevo.</strong>
        Son 12 preguntas; los errores se cuentan entre todas, no por pregunta.
      </p>
      <div class="quiz-mistakes" aria-label="${mistakes} de ${MISTAKE_LIMIT} errores">
        ${Array.from(
          { length: MISTAKE_LIMIT },
          (_, i) =>
            `<span class="${i < mistakes ? 'used' : ''}">${i < mistakes ? '×' : '○'}</span>`,
        ).join('')}
        <small>${mistakes} / 3 errores totales</small>
      </div>
      <h2 class="trivia-question">${question.question}</h2>
      <div class="choice-grid">
        ${options
          .map(
            (option, i) =>
              `<button class="choice quiz-answer ${reveal && option === question.correct ? 'selected' : ''}" data-choice="${i}" ${reveal ? 'disabled' : ''}>${option}</button>`,
          )
          .join('')}
      </div>
      <p class="feedback" role="status">
        ${
          message ||
          (reveal ? `${answers.at(-1).correct ? '¡Sí!' : 'Esta no.'} ${question.explanation}` : '')
        }
      </p>
      ${
        reveal
          ? '<div class="game-center"><button class="primary quiz-next">Siguiente pregunta →</button></div>'
          : ''
      }
    `;
    root.querySelectorAll('[data-choice]').forEach(
      (button) =>
        (button.onclick = () => {
          if (reveal) return;
          const choice = options[Number(button.dataset.choice)],
            correct = choice === question.correct;
          answers.push({ id: question.id, choice, correct });
          reveal = true;
          ctx.sound(correct ? 'pop' : 'wrong');
          if (answers.filter((answer) => !answer.correct).length === MISTAKE_LIMIT) {
            const previous = [...quiz];
            attempt++;
            quiz = createQuiz(stage.seed, attempt, previous);
            answers = [];
            reveal = false;
            save();
            paint(
              'Llegaste a tres errores en total. Intenta otra vez con estas 12 preguntas nuevas.',
            );
          } else {
            save();
            paint();
            root.querySelector('.quiz-next').focus();
          }
        }),
    );
    const next = root.querySelector('.quiz-next');
    if (next)
      next.onclick = () => {
        reveal = false;
        save();
        paint();
      };
  }
  save();
  paint();
}
